// script.js

const acts = {
  "Ato 1": [
  "Mate o Miller Inchado e entre na cidade",
  "Entregue as missões e vá para Clearfell",
  "Mate Beira do Rotten Pack. Ela está ao norte/nordeste do ponto de passagem. Recompensa: 10% Cold Res.",
  "Encontre a entrada para The Greilwood",
  "Encontre o waypoint e fale com o NPC da missão. Geralmente central.",
  "Encontre a entrada para The Grim Tangle, pegue o ponto de passagem e volte para The Greilwood",
  "Encontre a entrada para The Red Vale e siga em frente.",
  "Encontre os três obeliscos e pegue os três itens de missão.",
  "Depois de pegar o terceiro, vá para a cidade e fale com Renly para adquirir os Runed Spikes. Vá para The Greilwood.",
  "Invoque e fale com Una.",
  "Estafeie a árvore com seus espinhos rúnicos e depois fale com Una.",
  "Volte para a cidade, fale com os NPCs e depois siga para The Grim Tangle pelo ponto de passagem para The Greilwood.",
  "Encontre a entrada para o Cemetery of The Eternals. O chefe Druid pode ser pulado.",
  "Encontre o Mausoléu do Pretor e mate o chefe lá.",
  "Encontre o Túmulo do Consorte e mate o chefe lá dentro.",
  "Fale com Lachlan, abra o portão e mate-o. 😈",
  "Entre em Campos de Caça",
  "Encontre e mate The Crowbell. Recompensa: dois pontos de habilidade.",
  "Encontre e entre em Ogham Farmlands.",
  "Encontre o alcaide de Una. Geralmente no redor do centro da zona. Recompensa: 2 pontos de habilidade.",
  "Encontre e mate Vargl The Feral Mutt no Crop Circle. Deixa cair uma gema de habilidade de nível 4.",
  "Volte entre os campos paralelos para Ogham Village e WP de volta para Hunting Grounds.",
  "Encontre e insira Freython.",
  "Faça todos os 4 rituais, matando The King in the Mists no final. Recompensa: 30 espíritos.",
  "TP de volta à cidade e ponto de referência para Ogham Village.",
  "Se for seu primeiro personagem de liga: encontre ferramentas de ferraria.",
  "Encontre e mate o Carrasco",
  "Vá para as muralhas da mansão",
  "Encontre a entrada para Ogham Manor. Ela sempre fica na direção oposta do ponto de passagem depois que você entra na zona.",
  "Encontre e mate Candlemass, o Rito Vivo",
  "Encontre o elevador e desça as escadas duas vezes",
  "Encontre o elevador para o chefe, mate o chefe e volte para a cidade",
  "Se for seu primeiro personagem de liga: Fale com Renly para entregar as ferramentas de ferraria",
  "Fale com o Encapuzado para ir para o ato 2"
],
  "Ato 2": [
  "Encontre e mate Bathrarr",
  "Fale com todos e use o mapa de deserto para ir para a Pedreira Mavoun",
  "Encontre a passagem secreta para a Mina Mavoun",
  "Encontre e mate Bodil, o Engenheiro do Terror",
  "Fale com Bodi e desbloqueie o pilar na cidade",
  "Fale com Glaus, use o mapa do deserto para ir até Hadean Gates",
  "Complete os objetivos, ative os pilares e libere a porta para Hadean Gates. Mate o chefe lá dentro",
  "Volte para cidade, fale com os NPCs e siga para Passagem do Traidor",
  "Encontre e enfrente Djinn Baya",
  "Encontre os três pontos em Hakanai. Fique perto do chefe. Cuidado: 3 vezes para encontrar o chefe.",
  "Entregue as missões e vá para cidade",
  "Encontre a entrada para o julgamento de Sekhema",
  "Lute contra Sekhema e sua legião. Recompensa: 3 pontos de habilidade.",
  "TP de volta à cidade e entre na Cidade Perdida",
  "Encontre e entre no Santuário Enferrujado, depois vá para o coração de Keth",
  "Mate Karstir, o Olho Abandonado",
  "Fale com Illidan, no Oásis de Areia, complete os rituais e colete a recompensa",
  "Volte para cidade e fale com os NPCs",
  "Use o mapa do deserto para ir para Mantedor Bandana",
  "Encontre a entrada para The Stone Pits",
  "Mate os chefes e ative os esquisitos cristais",
  "Mate os rituais de essência. Recompensa: 1 slot de skill",
  "TP de volta e entre na Vale dos Titãs",
  "Complete os desafios e as ruínas antigas",
  "Receba o máximo de cultos e ganhe habilidade. Recompensa: um buff permanente.",
  "Encontre a relíquia e entre na Gruta do Titi",
  "Complete os objetivos da caverna e volte para a cidade",
  "Entre em Denhar",
  "Mate os chefes e campeões da caverna. Recompensa: 2 pontos de habilidade ou mais",
  "Siga o Caminho do Luto",
  "Encontre os chefes finais em The Spire of Despair",
  "Derrote Goli, o Desespero",
  "TP de volta à cidade",
  "Encontre entrada em Dreadnought",
  "Complete todas as seções do Dreadnought, enfrente e mate Jarnam, a Abominação",
  "Volte para cidade e fale com Sazhan",
  "Fale com o Encapuzado e entre no Ato 3"
  ],
  "Ato 3": [
    "Encontre a entrada para o Acampamento Ziggurat (cidade)",
  "Fale com todos e entre na Floresta de Salta",
  "Encontre a entrada para Twin Worm Crypts (próxima ao ponto de passagem)",
  "Encontre e colete os Pedaços Perdidos de Tributo",
  "Encontre e enfrente Chief Wuntho. Entre na zona, pegue o waypoint, volte para tributar Renna",
  "Encontre a entrada para Twin Rock Hill, pegue o waypoint, lute contra tribos, mate o chefe",
  "Siga para The Maiden Walkway e derrote o chefe da floresta",
  "Volte para o acampamento e entregue os tributos, siga para Return of Salta",
  "Encontre a entrada para Djin Baya",
  "Complete o desafio e volte para cidade",
  "Encontre a entrada para Serid",
  "Complete os tributos em Serid para receber uma recompensa. Isso não pode ser alterado depois.",
  "Use WP para Twin Rock Hill",
  "Use o altar de Azak, que dá 25% de resistência ao fogo e redefina para o início da zona",
  "Vá para a entrada principal da Chained Walkway",
  "Complete todas as lutas tribais e vá para Keth",
  "Encontre tribos Jaqari, e derrote Wantu",
  "Entre no Mechanarium de Jaqari",
  "Complete o desafio e entre no Santuário de Jaqari",
  "Não se esqueça de ativar o waypoint logo após a entrada",
  "Fale com Akiri",
  "Faça as arenas tribais, derrote o Guardião ANTES de ativar o segundo guardião",
  "Complete os desafios e colete as relíquias no Santuário de Jaqari",
  "Wantu Zosculi (Guardião de Molten) será o chefe final",
  "Volte para Merchant's Refuge e fale com os líderes tribais",
  "Entre novamente na The Maiden Walkway depois",
  "Ative cada waypoint para preparar para a disputa da grande final",
  "Vá até o final da zona",
  "Use o acesso da cidade pelo / Desacorde",
  "Entre na Cidade Afogada",
  "Se for seu primeiro personagem de liga: Encontre a entrada para The Molten Vault. Entre na zona, pegue o waypoint, volte para The Drowned City.",
  "Encontre o altar The Altar of Fire. Entra e volta, pequena recompensa, se não for seu primeiro personagem de liga, volte para The Drowned City.",
  "Use o waypoint e entre na última luta de arena tribal. Use certificado, entre na The Altar of Fire.",
  "Complete os desafios",
  "Entre na Cidade Afogada e fale com Osseiri na cidade",
  "Fale com Zana",
  "Encontre ruínas Relíquia da Sufrida, entre para o desafio",
  "Use o acesso da cidade pelo / Desacorde novamente e entre no Templo de Kopec",
  "Entre no Templo de Kopec",
  "Se não acessado ainda, use o waypoint e entre na sala Kantu, Sumo Sacerdote do Sol",
  "Fale com Akira e aceite o desafio",
  "Fale com portal e colete recompensa antes de entrar em Urzaal",
  "Entre em Urzaal",
  "Procure entrada entre Agganati e entre em Aggari",
  "Complete as arenas tribais em Aggari",
  "Complete o desafio e ative todos os portais, acione o próximo ponto de verificação",
  "Use o waypoint e entre no The Black Chamber",
  "Complete o ritual de verificação: mate os mini-chefes, colete as orbes, acione o coração, estacione e conclua",
  "Volte para cidade e fale com os líderes tribais sobre The Black Chambers",
  "Complete as verificações finais",
  "Entre nas Câmaras Negras",
  "Derrote os chefes Deyanil, Tumortuga final",
  "Fale com os líderes da cidade e entre no portal para o Ato 4 final"
  ],
  "Ato 4": [
    "Mate o Miller Inchado e entre na cidade",
  "Entregue as missões e vá para Clearfell",
  "Mate Beira do Rotten Pack. Ela está ao norte/nordeste do ponto de passagem. Recompensa: 10% Cold Res.",
  "Encontre a entrada para The Greilwood",
  "Encontre o waypoint e fale com o NPC da missão. Geralmente central.",
  "Encontre a entrada para The Grim Tangle, pegue o ponto de passagem e volte para The Greilwood",
  "Encontre a entrada para The Red Vale e siga em frente.",
  "Encontre os três obeliscos e pegue os três itens de missão.",
  "Depois de pegar o terceiro, vá para a cidade e fale com Renly para adquirir os Runed Spikes. Vá para The Greilwood.",
  "Invoque e fale com Una.",
  "Estafeie a árvore com seus espinhos rúnicos e depois fale com Una.",
  "Volte para a cidade, fale com os NPCs e depois siga para The Grim Tangle pelo ponto de passagem para The Greilwood.",
  "Encontre a entrada para o Cemetery of the Eternals. O chefe Druid pode ser pulado.",
  "Encontre o Mausoléu do Pretor e mate o chefe lá.",
  "Encontre o Túmulo do Consorte e mate o chefe lá dentro.",
  "Fale com Lachlan, abra o portão e mate-o. 😈",
  "Entre em Campos de Caça",
  "Encontre e mate The Crowbell. Recompensa: dois pontos de habilidade.",
  "Encontre e entre em Ogham Farmlands.",
  "Encontre o alcaide de Una. Geralmente no redor do centro da zona. Recompensa: 2 pontos de habilidade.",
  "Encontre e mate Vargl The Feral Mutt no Crop Circle. Deixa cair uma gema de habilidade de nível 4.",
  "Encontre e siga pela entrada para Ogham Village.",
  "Encontre e insira Freython.",
  "Faça todos os 4 rituais, matando The King in the Mists no final. Recompensa: 30 espíritos.",
  "TP de volta à cidade e ponto de referência para Ogham Village.",
  "Se for seu primeiro personagem de liga: encontre ferramentas de ferraria.",
  "Encontre e mate o Carrasco",
  "Vá para as muralhas da mansão",
  "Encontre a entrada para Ogham Manor. Ela sempre fica na direção oposta do waypoint depois que você entra na zona.",
  "Encontre e mate Candlemass, o Rito Vivo",
  "Desça as escadas duas vezes",
  "Encontre o elevador para o chefe, mate o chefe e volte para a cidade",
  "Fale com o Encapuzado para ir para o ato 2"
  ],
  "Ato 5": [
    "Encontre e mate Bathrarr",
  "Fale com todos e use o mapa de deserto para ir para a Pedreira Mavoun",
  "Encontre a passagem escondida para a Mina Mavoun",
  "Encontre e mate Bodil, o Engenheiro do Terror",
  "Fale com Bodil e desbloqueie o pilar na cidade",
  "Fale com Sokeham Aata e siga para o deserto para ir até The Hadean Gates",
  "Fale com Sokeham Aata novamente, pegue os cristais, use-os nas colunas, mate os inimigos, depois com Sokeham Aata novamente",
  "Volte para cidade e prepare-se para movimentar para Twin Hadean Gates",
  "Encontre a entrada para Twin Hadean Gates",
  "Enfrente os desafios e enfrente Djinn Baya",
  "Complete os desafios e volte para cidade",
  "Fale com todos e use o mapa do deserto para ir até Keth",
  "Encontre tribos, colete os tributos",
  "Enfrente inimigos Jaqari, e derrote o Guardião",
  "Encontre e entre no Cidade Perdida",
  "Encontre e enfrente Kalasha, Justiça Corrompida. Recompensa: 2 pontos de habilidade.",
  "Volte para cidade",
  "Encontre a entrada para Santuário Enferrujado, depois para o coração de Keth",
  "Mate Karstir, o Olho Abandonado",
  "Fale com Illidan, no Oásis de Areia, siga para os cristais, queime a chama e derrote a essência na água",
  "Volte para cidade",
  "Use o mapa do deserto para ir para Mantedor Bandana",
  "Encontre a entrada para The Stone Pits",
  "Descubra os rituais e chefes e complete os desafios",
  "Mate os chefes da essência e realize o ciclo de skill",
  "TP de volta e entre em Vale dos Titãs",
  "Encontre o chefe final no altar",
  "Complete a relíquia e enfrente as tribos adicionais. Recompensa: um buff permanente.",
  "Encontre e pegue a relíquia em Gruta do Titi",
  "Complete os desafios da caverna e volte para cidade",
  "Entre em Denhar",
  "Encontre e elimine todos os campeões do culto. Recompensa: dois pontos de habilidade ou mais",
  "Siga o Caminho do Luto",
  "Encontre os chefes finais em Trono do Desespero",
  "Derrote Goli, o Desespero",
  "TP de volta para cidade",
  "Encontre entrada para Geshtani",
  "Complete os desafios no Geshtani",
  "Fale com o portal final e prepare-se para entrada final no título dreadnought",
  "Entre no Dreadnought",
  "Derrote os guardas e elites do Dreadnought, então encontre e mate Jarnam, a Abominação",
  "Volte para The Arisen Citadel e fale com Sokeham Aata",
  "Fale com Sokeham e entre no portal para o Ato 6"
  ],
  "Ato 6": [
    "Encontre a entrada para o Acampamento Ziggurat (cidade)",
  "Fale com todos e entre na Floresta de Salta",
  "Encontre a entrada para Twin Worm Crypts (próxima ao ponto de passagem)",
  "Encontre e colete os Pedaços Perdidos de Tributo",
  "Encontre e enfrente Chief Wuntho. Entre na zona, pegue o waypoint, volte para tributar Renna",
  "Encontre a entrada para Twin Rock Hill, pegue o waypoint, lute contra tribos, enfrente o chefe",
  "Siga para The Maiden Walkway e derrote o chefe final da floresta",
  "Volte ao acampamento, entregue os tributos, siga para Return of Salta",
  "Encontre a entrada para Djin Baya",
  "Complete o desafio e volte para cidade",
  "Encontre a entrada para Serid",
  "Complete os tributos em Serid para receber uma recompensa. Isso não pode ser alterado depois",
  "Use WP para The Azak",
  "Use o altar em Azak para reduzir 25% de resistência ao fogo e redefinir para o início da zona",
  "Vá para a entrada principal da The Chained Walkway",
  "Complete os desafios tribais e vá até Keth",
  "Encontre tribos Jaqari, e derrote Wantu",
  "Entre no Mechanarium de Jaqari",
  "Complete o desafio e entre no Santuário de Jaqari",
  "Não se esqueça de ativar o waypoint logo após a entrada",
  "Fale com Akiri",
  "Faça as arenas tribais",
  "Vá até o altar dos cristais. Complete o portal ANTES de ativar o segundo guardião",
  "Colete os orbes elementais e continue os desafios",
  "Fale com Zosculi, Guardião de Molten, enfrente e derrote-o",
  "Volte para cidade e prepare-se para entrar na Hadean Barrens",
  "Entre novamente na The Maiden Walkway depois",
  "Ative cada waypoint para preparar para a disputa da grande final",
  "Vá até o final da zona",
  "Use o acesso da cidade pelo / Desacorde",
  "Entre na Cidade Afogada",
  "Encontre a entrada para The Altar of Fire. Entre na zona, pegue o waypoint. Se for seu primeiro personagem da liga, entre pelo The Drowned City.",
  "Encontre e derrote os desafios em The Altar of Fire",
  "Use o altar e derrote o mini chefe",
  "Complete os desafios, enfrente os líderes tribais",
  "Volte para cidade",
  "Encontre entrada Relíquia da Sufrida, entre nela e fale com Zana",
  "Use o acesso da cidade pelo / Desacorde novamente e entre no Templo de Kopec",
  "Entre no Templo de Kopec",
  "Use os acessos e entre na arena contra Kantu, Sumo Sacerdote do Sol",
  "Fale com Akira e aceite o desafio",
  "Fale com portal e colete recompensa antes de entrar em Urzaal",
  "Entre em Urzaal",
  "Procure entrada entre Agganati e entre em Aggari",
  "Complete as arenas tribais de Aggari",
  "Complete o desafio e ative os portais, acesse o próximo ponto de verificação",
  "Use o waypoint e entre em The Black Chambers",
  "Complete o ritual de verificação: mate os mini-chefes, colete as orbes, acione o coração, estacione e conclua",
  "Volte para cidade e fale com os líderes tribais sobre The Black Chambers",
  "Complete as verificações para entrar no The Black Chambers, entre em The Black Chambers",
  "Derrote os chefes Deyanil, Tumortuga final",
  "Volte para a cidade e entre no portal com Zana para terminar a campanha!"
  ]
};

const checklistContainer = document.getElementById('checklist');
checklistContainer.innerHTML = "";

Object.entries(acts).forEach(([act, objectives]) => {
  const section = document.createElement('section');
  const h2 = document.createElement('h2');
  h2.textContent = act;
  section.appendChild(h2);

  const ul = document.createElement('ul');
  ul.className = 'checklist';

  const savedState = JSON.parse(localStorage.getItem('poe2_checklist_state_' + act)) || {};

  objectives.forEach((text, index) => {
    const li = document.createElement('li');
    li.textContent = text;
    if (savedState[index]) li.classList.add('checked');

    li.addEventListener('click', () => {
      li.classList.toggle('checked');
      savedState[index] = li.classList.contains('checked');
      localStorage.setItem('poe2_checklist_state_' + act, JSON.stringify(savedState));
    });

    ul.appendChild(li);
  });

  section.appendChild(ul);
  checklistContainer.appendChild(section);
});
